### ISSUE TITLE
好赞！！不知道后续有没有对server层面和整机层面的统计？

### ISSUE THREAD

**Issue by fankeke** [GuyCheung/falcon-ngx_metric#13]
看了下代码，写得很赞，学习了很多，特别是对sample抽样部分。
有两个问题请教下：

1，目前这个统计是针对uri（location）层面的，我打算将其扩展到可以统计server层和http层的，不知道有啥难度没？（估计应该是没啥难度的，代码的耦合度都很低，很方便扩展）

2，另外，是否可以按照每个upstream的名字统计下每个upstream的counter和time? 这样更具体详细。
(粗略看了下，目前只是按照uri对相应的upstream进行了time的统计,获取upstream的名字会是难点么？）

**Comment by GuyCheung** [comment]
@fankeke 谢谢支持

> 目前这个统计是针对uri（location）层面的，我打算将其扩展到可以统计server层和http层的，不知道有啥难度没？

这个目前我们内部已经可用了，我整理下更新出来

> 另外，是否可以按照每个upstream的名字统计下每个upstream的counter和time? 这样更具体详细。
(粗略看了下，目前只是按照uri对相应的upstream进行了time的统计,获取upstream的名字会是难点么？）

这个目前我们内部也已经支持了，但是upstream的名字需要打一个nginx的patch才能支持哈，可以参考这个 https://github.com/openresty/lua-nginx-module/issues/301

**Comment by kenhq03** [comment]
请问这两个功能的版本还有开源计划吗，从监控的层面看整体的数据也是很有必要的，希望新版本能完善，谢谢！
