### ISSUE TITLE
请问yum安装完nginx ${NGINX_HOME} 路径具体是哪？ 这个错误是什么原因呢Starting nginx: nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/conf.d/ngx_metric.conf:2

### ISSUE THREAD

**Issue by map-libc** [GuyCheung/falcon-ngx_metric#2]

**Comment by itxx00** [comment]
你安装的nginx没有lua模块

**Comment by map-libc** [comment]
latency_50th/api=  这种指标具体是什么意思呢 比如说value为0.001 该怎么理解，是50次请求的平均延时为0.001秒吗

**Comment by milk531** [comment]
比如你有100个用户，这100个用户请求响应时间从低到高排序后取第50个用户的响应值就是50th，也就是说你有一半用户的响应时间是好于这个值的。

**Comment by map-libc** [comment]
谢谢回答，问句废话，那如果这段时间内有200个用户请求 ，50th 就代表是第100个用户的请求响应时间呗

**Comment by milk531** [comment]
不是第100个用户，而是第100个快的用户，根据响应时间长短排过序的。可以搜百分位数了解下这个概念，我最开始也是蒙的，看了之后就清楚了。


原始邮件
发件人:map-libcnotifications@github.com
收件人:GuyCheung/falcon-ngx_metricfalcon-ngx_metric@noreply.github.com
抄送:wenxiokwenxi@gmail.com; Commentcomment@noreply.github.com
发送时间:2016年6月21日(周二) 11:39
主题:Re: [GuyCheung/falcon-ngx_metric] 请问yum安装完nginx ${NGINX_HOME} 路径具体是哪？ 这个错误是什么原因呢Starting nginx: nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/conf.d/ngx_metric.conf:2 (#2)


谢谢回答，问句废话，那如果这段时间内有200个用户请求 ，50th 就代表是第100个用户的请求响应时间呗
