### ISSUE TITLE
字符错误

### ISSUE THREAD

**Issue by spark8899** [GuyCheung/falcon-ngx_metric#25]
客户端打这种请求： { "timestamp": "2018-04-18T01:02:34+08:00", "host": "xx.xx.xx.xxx", "user": "-", "request": "\x16\x03\x01\x00\xDA\x01\x00\x00\xD6\x03\x03\xAD\x03\x99&*{\xAB\xAB\x8C\x1DS\x82\xCF\xA4y\xCF\x84\xB4\xEB\xAF}\x93S,u\xD4\xB5\x1E\x10\xB2\xE5;\x00\x00(\xC0,\xC0+\xC0$\xC0#\xC0", "clientip": "xx.xxx.xx.xxx", "size": 166, "responsetime": 5.000, "upstreamtime": "-", "upstreamhost": "-", "upstreamstatus": "-", "http_host": "_", "url": "-", "referrer": "-", "x_forwarded_for": "-", "agent": "-", "status": "400"}

error日志会有这种错误
2018/04/18 10:02:30 [error] 124908#124908: *4252054 failed to run log_by_lua*: /usr/local/nginx/modules/ngx_metric/util.lua:49: bad argument #1 to 'gmatch' (string expected, got nil)
stack traceback:
	[C]: in function 'gmatch'
	/usr/local/nginx/modules/ngx_metric/util.lua:49: in function 'str_split'
	.../local/nginx/modules/ngx_metric/ngx_metric.lua:12: in function 'cut_uri'
	.../local/nginx/modules/ngx_metric/ngx_metric.lua:24: in function 'new'
	/usr/local/nginx/modules/ngx_metric.lua:16: in function </usr/local/nginx/modules/ngx_metric.lua:1> while logging request, client: xxx.xx.xx.xxx, server: _, request: "µ±Z֧68Ӝe^,>c5T~쀍"

**Comment by johnlau3** [comment]
2018/06/15 08:33:55 [error] 24436#0: *728917834 failed to run log_by_lua*: modules/ngx_metric/util.lua:49: bad argument #1 to 'gmatch' (string expected, got nil)
stack traceback:
        [C]: in function 'gmatch'
        modules/ngx_metric/util.lua:49: in function 'str_split'
        modules/ngx_metric/ngx_metric.lua:12: in function 'cut_uri'
        modules/ngx_metric/ngx_metric.lua:24: in function 'new'
        /home/worker/nginx/modules/ngx_metric.lua:16: in function </home/worker/nginx/modules/ngx_metric.lua:1> while logging request, client: xxx.xx.14.41, server: xxx.xxx.xxx.com, request: "CONNECT xxx.xxx.126.119:43 HTTP/1.1"
我也遇到了

**Comment by spark8899** [comment]
...
