### ISSUE TITLE
python脚本运行报错

### ISSUE THREAD

**Issue by leeypp** [GuyCheung/falcon-ngx_metric#3]
Traceback (most recent call last):
  File "nginx_collect.py", line 450, in collect
    append_datapoint(datapoints, Render.render(la))
  File "nginx_collect.py", line 70, in render
    c = renders[la[0]]
KeyError: '<html>'

**Comment by leeypp** [comment]
经过查看nginx日志可以发现问题所在
cp ${NGINX_HOME}/falcon-ngx_metric/lua/ngx_metric/ngx_metric -R /usr/share/lua/5.1/
即可解决

**Comment by wujunlin555** [comment]
我跟你一摸一样的错误 用你的方法 行不通  困扰好久

**Comment by gogogonnn** [comment]
*.lua的路径找不到，查一下nginx的error日志调一下路径
